### ISSUE TITLE
Checklist for wed

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#662]
- [x] Ensure production is running the latest code
 - [x] Scaling groups for panoptes apis
 - [x] Adjust retirement rules based on data loads
 - [x] Zoo home DB scaling
 - [x] Zoo home API scaling
 - [x] Check mini seach handles load
 - [x] PreScale Cellect prod
 - [x] Ensure Cellect loads the workflow data start for on each node
 - [x] Warm the ELB's for prodcution
 - [x] Aggregation Production configs
 - [x] Ensure Ec2 nodes have enough resources (Cellect and API)

Feel free to add stuff i've forgotten about.
